### ISSUE TITLE
Any plans to make this avaible for the JS backend?

### ISSUE THREAD

**Issue by halloleo** [guzba/zippy#17]
As a pure Nim implementation, are there any plans to make this available for the JS backend?

**Comment by guzba** [comment]
It is something I'd like to be able to do in the future, but it is not a quick thing right now. Zippy goes to great lengths to be fast since compressing and decompressing are pretty performance critical things. Targetting JS greatly limits what can be done so I'd have to write a JS path for many areas. It may happen someday, but it would come after a next major release where I supported streams and other functionality improvements first.

**Comment by guzba** [comment]
Adding this here for record: https://github.com/guzba/zippy/issues/14

**Comment by halloleo** [comment]
Fair enough. After all there are [JS zip libraries](https://gildas-lormeau.github.io/zip.js/) which can be wrapped in Nim.
