### ISSUE TITLE
Create zipfile in memory.

### ISSUE THREAD

**Issue by enthus1ast** [guzba/zippy#35]
It would be nice to have a procedure that just returns the binary of a zipfile instead of writing to disk.

**Comment by guzba** [comment]
This 100% makes sense. The current zip archive and tarball implementation is pretty basic, I mostly wanted to learn how they work and figured a basic thing is better than nothing. I now know how to do both much better and will be making improvements over time, including this option to get a zip archive blob without writing to disk.

**Comment by enthus1ast** [comment]
Should i leave this issue open for documenting/referencing?

**Comment by guzba** [comment]
Yep that's fine, can use this for updates unless you'd prefer to close it.

**Comment by mashingan** [comment]
For easiest changes without changing much the implementation is by changing [writeZipArchive](https://github.com/guzba/zippy/blob/master/src/zippy/ziparchives_v1.nim#L346-L348) to `$` (which returns string) or `write` (name can be vary) which returns `seq[uint8]` , [change it to return the `data`](https://github.com/guzba/zippy/blob/master/src/zippy/ziparchives_v1.nim#L458-L461) instead of directly writing it to file, and have the actual `writeZipArchive` reuses it:

```nim
proc writeZipArchive*(archive: ZipArchive, path: string) =
    path.writeFile($archive) # or path.writeFile(archive.write)
```

This way we still have the same `writeZipArchive` works as is.
