### ISSUE TITLE
Error Cross Compiling on Linux AMD64 -> aarch64

### ISSUE THREAD

**Issue by hortinstein** [guzba/zippy#57]
```
/home/hortinstein/.cache/nim/cross_compile_d/@m..@s..@s.nimble@spkgs@szippy-0.10.3@szippy@sadler32_simd.nim.c:9:10:
fatal error: arm_neon.h: No such file or directory
    9 | #include "arm_neon.h"
```
I am getting the following issue when I try to compile, here is a reproduction:
https://github.com/hortinstein/cross_compile
```nimble buildmobile```

**Comment by guzba** [comment]
I do not know what config or requirements there are to make cross compiling from amd64 to arm64 work. Something is not correct now because the NEON header is not present for some reason for SIMD. I will not be working on this unless something changes and I need it personally as fighting with compiler config is not something I enjoy.
